### ISSUE TITLE
generator_loss的使用和论文中不一样

### ISSUE THREAD

**Issue by donb123asfdojdas** [ZongqiLiuphd/GAN-MMC#1]
在这个模型对应的论文中generator_loss是有三部分组成，包括基于判别器（Discriminator）生成的0-1之间的结果，但是在代码中获得generator_loss时没有调用判别器，请问这是为什么呢？
![微信截图_20241108184747](https://github.com/user-attachments/assets/51af9da7-21c9-4ecb-ac8b-233a3a57d50f)
![微信截图_20241108184857](https://github.com/user-attachments/assets/43993533-1fd8-4fc5-a70b-e383dcbd9ba3)

**Comment by ZongqiLiuphd** [comment]
十分感谢您让我注意到这个重大的问题，我由于疏忽上传代码错误，误将对不利用GAN结构的测试代码上传，我已经更新文件，将正确的代码上传了，再次感谢您对本人问题的指出，欢迎交流

**Comment by donb123asfdojdas** [comment]
嗯嗯，好的谢谢您
