### ISSUE TITLE
代码中的GAN和论文中的不一样

### ISSUE THREAD

**Issue by goudanwb** [ZongqiLiuphd/GAN-MMC#2]
代码中的GAN和论文中的不一样。
<img width="523" alt="3b7c656e700eef3cdbb14ff83d78c65" src="https://github.com/user-attachments/assets/97e8acb1-d67c-4dce-8111-59a80b663bdf">
<img width="329" alt="614e7c6d376f9d761a72bf1a0da2504" src="https://github.com/user-attachments/assets/fcbcc1fe-3be0-4359-bba4-2c7180d65c83">
<img width="331" alt="fc8ac06b69b2851fe37a019f7c6c06d" src="https://github.com/user-attachments/assets/fe2194cf-a61d-4a95-8c10-d3b0b7ed7f1c">

**Comment by ZongqiLiuphd** [comment]
感谢您指出该问题，因为更换过电脑所以代码上传的还是有问题，我稍后会仔细检查更新代码

**Comment by ZongqiLiuphd** [comment]
代码已进行了更新，由于代码已经过多次更改，不确定是否为最终原版，但目前代码已符合论文中大体框架，可帮助理解论文，如进一步应用，建议在模型基础上选择合适的网络结构和参数。十分感谢您对本人论文感兴趣，如有问题欢迎进一步讨论

**Comment by goudanwb** [comment]
谢谢 非常感谢您

**Comment by goudanwb** [comment]
谢谢 非常感谢您
